### ISSUE TITLE
Static pages outside the public dir?

### ISSUE THREAD

**Issue by joesho112358** [newtewt/chapter_3#1]
Static pages go in the `/public` directory, no real need to have the title set in the view that way vs a true static page... hopefully the book gets to that later! Or maybe you'll get a dynamic header/footer based on a logged in user?! I am on the edge of my seat!

**Comment by newtewt** [comment]
Closed no issues opened after 12 am will be accepted.

**Comment by joesho112358** [comment]
Everything happens after 12 AM!
